### ISSUE TITLE
How to build scenario tree from historical data

### ISSUE THREAD

**Issue by ridongwang** [julienkeutchayan/StochOptim#1]
I try to do a multi-stage optimization. And I have historical data about uncertainty. Is there any example which can show how to construct the scenario tree using these historical data? Or which function should I use?

**Comment by julienkeutchayan** [comment]
Currently there is no tool to construct multistage scenario tree from historical data in StochOptim (only (1) multistage from distribution and (2) two-stage from historical data). So one possibility would be to infer a distribution from your data and apply (1). Another possibility is to use a more standard "distribution-driven approach" like SCENRED2 (available in GAMS).
